### PR TITLE
fixed footer component

### LINKED ISSUE #50: [BUG] bottom panel not working as intended
**Describe the bug**
The bottom panel in the website doesn't behave as it should be there are minor bugs that are described below.
1. The GitHub icon not redirecting to `https://github.com/code-gambit`, for the rest of the social icons it's fine redirecting to the same website until we have them setupped.
2. Hovering over an icon should display text telling the user what this icon does.
3. Clicking on the UI mode switch only changes icons but doesn't have any effect on UI.
4. The setting icon leads the user to the profile section, instead, the icon must be updated to profile, or it must redirect to the settings section.
5. Emai lid should be a hyperlink of type email, instead os static text.

**Screenshot**
Screenshot 2021-06-05 at 5 49 16 AM

Area Where Bug Occurred

- [x] UI/UX
- [x] Business Logic

**How to reproduce the error/bug**
1. Open `https://vt-webclient.herokuapp.com/`
2. Click on icons in the bottom panel to observe the bugs mentioned in description section (point 1 to 5)

**Before submitting an issue check the below**

- [x] I have synced all my node versions as mentioned in the project"
- [x] I am using the same version of npm as is the project
- [x] My current branch is in sync with the development branch

### PR DESCRIPTION
**Pull request by ayush0x00**
# Description

Modified footer component to add auth features.

Fixes a section of #50 #38 

## Type of change

Please delete options that are not relevant.

- [x] Updated UI/UX
- [ ] Improved the business logic of code
- [x] Added new feature
- [ ] Other

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by lakshya-20 — COMMENTED** [review]
image

This tab modal is not responsive in small devices, so add a modal header like `Update` or `change` or `whats looks suitable` and remove that change from tab headings. It will work then.

**Comment by lakshya-20** [comment]
- #50  is linked but not resolved with this PR. Any of the mentioned requirements are not fulfilled by this PR.
- #38 says to implement Forgot password feature but it is not done.

**Review by lakshya-20 — CHANGES_REQUESTED** [review]
Your Footer
image

The current deployed Footer
image
The above snips are taken from the same screen ratio.
Notice the difference in the gap around toggle icons.

**Review by lakshya-20 — CHANGES_REQUESTED** [review]
https://user-images.githubusercontent.com/39180629/120933125-483b8400-c716-11eb-96d4-c6c59b754744.mp4

Reset the states when switching the tabs.

**Comment by lakshya-20** [comment]
@ayush0x00 don't forget to add labels and adding this PR to the project.

**Review by danishjamal104 — DISMISSED** [review]
Looks good, make sure the footer icons and email have valid redirecting URLs.

**Comment by danishjamal104** [comment]
@ayush0x00 , please rebase.

File: src/Components/Footer.js [hunk 1]
```diff
@@ -1,58 +1,325 @@
...
+import React, { useState, useContext } from "react";
+import { useHistory } from "react-router-dom";
+import { AuthContext } from "../Context/Contexts/AuthContext";
+import * as AuthActionCreators from "../Context/ActionCreators/AuthActionCreater";
+import { Auth } from "aws-amplify";
+import classnames from "classnames";
+import {
+  Button,
+  Modal,
+  ModalHeader,
```
Comment (lakshya-20) [inline src/Components/Footer.js]: Don't import ModalHeader and ModalFooter they are not being used anywhere.

File: src/Components/Footer.js [hunk 2]
```diff
@@ -1,58 +1,325 @@
...
-    const toggleLightMode=()=>{
-        setIsDarkMode(!isDarkMode);
+  const [mainModal, setMainModal] = useState(false);
+  const toggleMain = () => {
+    setMainModal(!mainModal);
+    setError({});
+    setValues({});
+    setVisibility({});
+  };
+  const [code, sendCode] = useState(false);
```
Comment (lakshya-20) [inline src/Components/Footer.js]: This hook declaration is not used anywhere so remove it.

File: src/Components/Footer.js [hunk 3]
```diff
@@ -1,58 +1,325 @@
...
+                  toggleTab("2");
+                }}
+              >
+                Username
+              </NavLink>
+            </NavItem>
+          </Nav>
+          <TabContent activeTab={activeTab}>
+            <TabPane tabId="1">
+              <Form style={{ "margin-top": "5px" }} onSubmit={updatePassword}>
```
Comment (lakshya-20) [inline src/Components/Footer.js]: image

File: src/Components/Footer.js [hunk 4]
```diff
@@ -1,58 +1,325 @@
...
+                    />
+                    <span
+                      onClick={() => {
+                        toggleVisibility("curr");
+                      }}
+                      class="fa fa-fw fa-eye field_icon toggle-password m-n4"
+                    ></span>
+                  </div>
+                  {errors.current_password && (
+                    <p style={{ "text-align": "left" }}>
```
Comment (lakshya-20) [inline src/Components/Footer.js]: image

File: src/Components/Footer.js [hunk 5]
```diff
@@ -1,58 +1,325 @@
...
+                    />
+                    <span
+                      onClick={() => {
+                        toggleVisibility("pwd");
+                      }}
+                      class="fa fa-fw fa-eye field_icon toggle-password m-n4"
+                    ></span>
+                  </div>
+                  {errors.password && (
+                    <p style={{ "text-align": "left" }}>{errors.password}</p>
```
Comment (lakshya-20) [inline src/Components/Footer.js]: image

File: src/Components/Footer.js [hunk 6]
```diff
@@ -1,58 +1,325 @@
...
+                    />
+                    <span
+                      onClick={() => {
+                        toggleVisibility("cpwd");
+                      }}
+                      class="fa fa-fw fa-eye field_icon toggle-password m-n4"
+                    ></span>
+                  </div>
+                  {errors.confirm_password && (
+                    <p style={{ "text-align": "left" }}>
```
Comment (lakshya-20) [inline src/Components/Footer.js]: image

File: src/Components/Footer.js [hunk 7]
```diff
@@ -1,58 +1,325 @@
...
+                    }}
+                  >
+                    {" "}
+                    Update password{" "}
+                  </Button>
+                </FormGroup>
+              </Form>
+            </TabPane>
+            <TabPane tabId="2">
+              <Form style={{ "margin-top": "5px" }} onSubmit={updateUsername}>
```
Comment (lakshya-20) [inline src/Components/Footer.js]: image

File: src/Components/Footer.js [hunk 8]
```diff
@@ -1,58 +1,325 @@
...
+    const newName = e.target[0].value;
+    Auth.updateUserAttributes(user, {
+      name: newName,
+    })
+      .then((res) => {
+        toast.success("User name updated successfully");
+        toggleMain();
+      })
+      .catch((err) => toast.error(err.message));
+  };
```
Comment (lakshya-20) [inline src/Components/Footer.js]: Instead of requesting amplify to update the username first check locally is username empty or not than request.

File: src/Components/Footer.js [hunk 9]
```diff
@@ -1,58 +1,325 @@
...
+                <span
+                  className="fa fa-sign-out fa-lg "
+                  onClick={handleLogout}
+                ></span>
+
             </div>
+          ) : (
+            null
+          )}
+          <div className="col-12 col-sm-4 d-flex  align-items-center justify-content-center">v-transfer-demo@gmail.com</div>
```
Comment (lakshya-20) [inline src/Components/Footer.js]: Change this using email tag [Can refer to this](https://www.tutorialspoint.com/html/html_email_links.htm)

**Review by lakshya-20 — CHANGES_REQUESTED** [review]
Modularize the code, it becomes easy to understand the modular code and will help to add any new feature.

File: src/Components/Footer.js [hunk 10]
```diff
@@ -1,58 +1,314 @@
...
+                <span
+                  className="fa fa-sign-out fa-lg "
+                  onClick={handleLogout}
+                ></span>
+
             </div>
+          ) : (
+            null
+          )}
+          <div className="col-12 col-sm-4 d-flex  align-items-center justify-content-center"><a href = "mailto: code.gb.io@gmail.com">Send us an inbox</a></div>
```
Comment (lakshya-20) [inline src/Components/Footer.js]: Instead of "Send us an inbox" write the mail id.

**Review by lakshya-20 — CHANGES_REQUESTED** [review]
image
Show the errors with a meaningful message from the user point of view.

**Comment by lakshya-20** [comment]
@ayush0x00 do update your branch

**Review by lakshya-20 — APPROVED** [review]
LGTM
